Apply redirect to signup
HackSC/hibiscus pull request #320
Opened 2023-01-18 21:42 UTC by VictiniX888

### Description

(_What have been done/changed_)

- Users visiting the apply-2023 page while not logged in will be redirected to the signup page
- Remember path of URL that user tried to visit so that we can redirect back to the exact path

### Testing plan

(_How will we test the changes requested on this PR?_)

- [ ] ...

2023-01-18 23:42 UTC, snokpok requested changes
minor changes

2023-01-18 23:42 UTC, snokpok commented on libs/sso-client/src/lib/sso-client.ts
> +            `${process.env.NEXT_PUBLIC_SSO_URL}/api/unauthorized`
nit: use `getEnv()`

2023-01-18 23:42 UTC, snokpok commented on libs/sso-client/src/lib/sso-client.ts
> +    redirect ?? `${process.env.NEXT_PUBLIC_SSO_URL}/login`
use `getEnv()`

2023-01-18 23:42 UTC, snokpok commented on libs/sso-client/src/lib/sso-client.ts
> +    redirectUrl?: string,
nit: -> `unauthorizedRedirectUrl`

2023-01-19 03:28 UTC, VictiniX888 commented on libs/sso-client/src/lib/sso-client.ts
> +            `${process.env.NEXT_PUBLIC_SSO_URL}/api/unauthorized`
Done!

2023-01-19 03:28 UTC, VictiniX888 commented on libs/sso-client/src/lib/sso-client.ts
> +    redirect ?? `${process.env.NEXT_PUBLIC_SSO_URL}/login`
Done!

2023-01-19 03:28 UTC, VictiniX888 commented on libs/sso-client/src/lib/sso-client.ts
> +    redirectUrl?: string,
Done!

2023-01-19 03:30 UTC, snokpok approved these changes
lgtm

2023-01-19 03:30 UTC, merged