Identity portal
HackSC/hibiscus pull request #381
Opened 2023-01-30 05:15 UTC by VictiniX888

### Description

(_What have been done/changed_)

- Implement identity portal
- Closes HIB-147, HIB-148

### Testing plan

(_How will we test the changes requested on this PR?_)

- [ ] ...

2023-02-01 22:19 UTC, snokpok requested changes
some quick fixes

2023-02-01 22:19 UTC, snokpok commented on libs/hibiscus-supabase-client/src/index.ts
> +// type LeaderboardUpdate = Database['public']['Tables']['leaderboard']['Update'];
remove comment

2023-02-02 03:57 UTC, VictiniX888 commented on apps/dashboard/common/add-event.ts
> +  //Database['public']['Tables']['event_log']['Row'][]
Done!

2023-02-02 03:57 UTC, VictiniX888 commented on apps/dashboard/common/add-event-user-id.ts
> +  //Database['public']['Tables']['event_log']['Row'][]
Done!

2023-02-02 03:57 UTC, VictiniX888 commented on apps/dashboard/common/add-event.ts
> +  // }
Done!

2023-02-02 03:57 UTC, VictiniX888 commented on apps/dashboard/common/search-event-id.ts
> +  //Database['public']['Tables']['events']['Row'][]
Done!

2023-02-02 03:57 UTC, VictiniX888 commented on apps/dashboard/pages/identity-portal/attendee-event-scan/index.tsx
> +      // setIsAlertVisible(false);
Done!

2023-02-02 03:57 UTC, VictiniX888 commented on libs/hibiscus-supabase-client/src/index.ts
> +
Done!

2023-02-02 03:57 UTC, VictiniX888 commented on libs/hibiscus-supabase-client/src/index.ts
> +// type LeaderboardUpdate = Database['public']['Tables']['leaderboard']['Update'];
Done!

2023-02-02 03:58 UTC, VictiniX888 commented on tsconfig.base.json
> +      "@hibiscus/ui-portal": ["libs/ui-portal/src/index.ts"]
Yea removed

2023-02-02 03:58 UTC, VictiniX888 commented on package.json
> +    "react-router-dom": "^6.8.0",
Yea I think we accidentally added this lol I've removed it

2023-02-02 05:56 UTC, snokpok approved these changes
lgtm

2023-02-02 05:57 UTC, VictiniX888 commented
Oops

2023-02-02 17:54 UTC, VictiniX888 commented
Merging

2023-02-02 17:54 UTC, merged