Tim onboarding: complete CRUD tasks REST API
HackSC/hibiscus pull request #460
Opened 2023-04-06 02:45 UTC by t1mtw0

### Description

(_What have been done/changed_)

- Implemented Flask CRUD tasks REST API using sqlite3 per onboarding instructions
- Endpoints:
    - POST `/api/tasks/create`: create new task
    - GET `/api/tasks/get`: get all tasks
    - GET `/api/tasks/get/<int:id>`: get single task
    - PUT `/api/tasks/update/<int:id>`: update single task
    - DELETE `/api/tasks/delete/<int:id>`: delete single task

### Testing plan

(_How will we test the changes requested on this PR?_)

- NA

2023-04-06 02:52 UTC, snokpok requested changes
small changes

2023-04-06 02:52 UTC, snokpok commented on apps/onboarding-api/onboarding_api/app.py
> +@app.route("/api/tasks/create", methods=["POST"])
should remove the `/create` at the end because the method `POST` already indicates its an operation to create something

2023-04-06 02:52 UTC, snokpok commented on apps/onboarding-api/onboarding_api/app.py
> +@app.route("/api/tasks/get/<int:id>", methods=["GET"])
remove the `/get` because `GET` already indicates it's getting a resource

2023-04-06 02:52 UTC, snokpok commented on apps/onboarding-api/onboarding_api/app.py
> +@app.route("/api/tasks/get", methods=["GET"])
same with above comment

2023-04-06 02:52 UTC, snokpok commented on apps/onboarding-api/onboarding_api/app.py
> +@app.route("/api/tasks/delete/<int:id>", methods=["DELETE"])
remove `/delete` because DELETE method already says its deleting a resource

2023-04-06 02:52 UTC, snokpok commented on apps/onboarding-api/onboarding_api/app.py
> +@app.route("/api/tasks/update/<int:id>", methods=["PUT"])
remove `/update` due to PUT and same reason with above

2023-04-07 00:28 UTC, t1mtw0 reviewed
made endpoints RESTful

2023-04-10 03:01 UTC, closed without merging